from pathlib import Path

base = Path('/home/user/ym-laboratory/design-v1/mock')

# 01 landing
p = base / '01-landing.html'
text = p.read_text(encoding='utf-8')
text = text.replace(
"""  <div class=\"section\" style=\"margin-top:12px; padding:14px 18px; background:rgba(255,255,255,0.035)\">\n    <div style=\"display:flex; gap:14px; justify-content:space-between; align-items:center; flex-wrap:wrap;\">\n      <div>\n        <span class=\"chip role-b2c\" style=\"margin-bottom:8px\">일반 사용자 흐름</span>\n        <div style=\"font-weight:700; color:#fff; margin-bottom:4px\">지금 보는 메뉴는 해당 역할 기준으로 다시 정리된 화면입니다.</div>\n        <div style=\"font-size:13px; color:#9ca3b8\">체질 진단, 루틴, 발효, 뷰티, 구매 화면만 먼저 보이도록 정리했습니다.</div>\n      </div>\n      <div style=\"display:flex; gap:8px; flex-wrap:wrap;\"><button type=\"button\" class=\"chip role-b2b\" onclick=\"YMDesignMock.enterRole('expert','09-standard-7axis.html')\">7축 기준 보기</button><button type=\"button\" class=\"chip role-b2b\" onclick=\"YMDesignMock.enterRole('expert','13-pro-community.html')\">전문가 협업 보기</button><button type=\"button\" class=\"chip role-admin\" onclick=\"YMDesignMock.enterRole('admin','14-crm-admin.html')\">운영 화면 보기</button></div>\n    </div>\n  </div>""",
"""  <div class=\"section\" style=\"margin-top:12px; padding:16px 18px; background:linear-gradient(135deg, rgba(59,132,246,0.10), rgba(73,205,166,0.08)); border:1px solid rgba(73,205,166,0.18)\">\n    <div style=\"display:flex; gap:16px; justify-content:space-between; align-items:center; flex-wrap:wrap;\">\n      <div>\n        <span class=\"chip role-b2c\" style=\"margin-bottom:8px\">일반 사용자 시작 화면</span>\n        <div style=\"font-weight:800; color:#fff; margin-bottom:4px\">여기는 소비자용 첫 화면입니다.</div>\n        <div style=\"font-size:13px; color:#b8c6da\">처방 · 루틴 · 발효 · 뷰티 · 구매만 먼저 열리고, 전문가/운영 화면은 아래 별도 진입 버튼이나 접근 가드를 통해서만 들어갑니다.</div>\n      </div>\n      <div style=\"display:flex; gap:8px; flex-wrap:wrap;\"><button type=\"button\" class=\"chip role-b2b\" onclick=\"YMDesignMock.enterRole('expert','09-standard-7axis.html')\">전문가 모드 진입</button><button type=\"button\" class=\"chip role-admin\" onclick=\"YMDesignMock.enterRole('admin','14-crm-admin.html')\">운영자 모드 진입</button></div>\n    </div>\n  </div>""")
text = text.replace(
"""  <div class=\"section\">\n    <h2>역할별로 바로 들어가기</h2>\n    <div class=\"grid\">\n      <div class=\"card is-clickable\" onclick=\"window.location.href='02-dashboard.html'\">\n        <span class=\"chip role-b2c\" style=\"margin-bottom:8px\">일반 사용자</span>\n        <div class=\"title\">체질 진단 · 루틴 · 구매 흐름</div>\n        <div class=\"meta\">대시보드, AI 처방실, 전통발효, 뷰티, MILA 숍 중심으로 바로 확인합니다.</div>\n        <button type=\"button\" class=\"cta\" data-role-entry=\"consumer\" onclick=\"event.stopPropagation(); YMDesignMock.enterRole('consumer','02-dashboard.html')\">일반 사용자로 보기 →</button>\n      </div>\n      <div class=\"card is-clickable\" onclick=\"window.location.href='09-standard-7axis.html'\">\n        <span class=\"chip role-b2b\" style=\"margin-bottom:8px\">전문가·운영</span>\n        <div class=\"title\">기준 · 검증 · 협업 흐름</div>\n        <div class=\"meta\">7축 표준, 정규화, 매핑, 공동연구, 전문가 네트워크, 운영 CRM 중심으로 들어갑니다.</div>\n        <button type=\"button\" class=\"cta\" data-role-entry=\"expert\" onclick=\"event.stopPropagation(); YMDesignMock.enterRole('expert','09-standard-7axis.html')\">전문가 화면으로 보기 →</button>\n      </div>\n    </div>\n  </div>""",
"""  <div class=\"section\">\n    <h2>역할별로 바로 들어가기</h2>\n    <div class=\"grid\">\n      <div class=\"card is-clickable\" onclick=\"YMDesignMock.enterRole('consumer','02-dashboard.html')\" style=\"border-color:rgba(59,132,246,0.35); box-shadow:0 12px 28px rgba(59,132,246,0.10)\">\n        <span class=\"chip role-b2c\" style=\"margin-bottom:8px\">일반 사용자</span>\n        <div class=\"title\">체질 진단 · 루틴 · 구매 흐름</div>\n        <div class=\"meta\">대시보드, AI 처방실, 전통발효, 뷰티, MILA 숍 중심으로 바로 확인합니다.</div>\n        <div class=\"meta\" style=\"color:#9fd9c8\">누구나 바로 이용 가능</div>\n        <button type=\"button\" class=\"cta\" data-role-entry=\"consumer\" onclick=\"event.stopPropagation(); YMDesignMock.enterRole('consumer','02-dashboard.html')\">일반 사용자로 보기 →</button>\n      </div>\n      <div class=\"card is-clickable\" onclick=\"YMDesignMock.enterRole('expert','09-standard-7axis.html')\" style=\"border-color:rgba(101,176,210,0.38); box-shadow:0 12px 28px rgba(101,176,210,0.12)\">\n        <span class=\"chip role-b2b\" style=\"margin-bottom:8px\">전문가</span>\n        <div class=\"title\">기준 · 검증 · 공동연구 흐름</div>\n        <div class=\"meta\">7축 표준, 정규화, 매핑, 공동연구, 전문가 네트워크 중심으로 들어갑니다.</div>\n        <div class=\"meta\" style=\"color:#8cb6ea\">직접 URL 진입 시 접근 가드 표시</div>\n        <button type=\"button\" class=\"cta\" data-role-entry=\"expert\" onclick=\"event.stopPropagation(); YMDesignMock.enterRole('expert','09-standard-7axis.html')\">전문가 화면으로 보기 →</button>\n      </div>\n      <div class=\"card is-clickable\" onclick=\"YMDesignMock.enterRole('admin','14-crm-admin.html')\" style=\"border-color:rgba(215,200,18,0.30); box-shadow:0 12px 28px rgba(215,200,18,0.10)\">\n        <span class=\"chip role-admin\" style=\"margin-bottom:8px\">운영자</span>\n        <div class=\"title\">구독 · VIP · 캠페인 운영 흐름</div>\n        <div class=\"meta\">운영 CRM, 이탈위험 관리, 캠페인 실행, 매출 관리를 전용으로 확인합니다.</div>\n        <div class=\"meta\" style=\"color:#d7c812\">운영 전용 가드 후 진입</div>\n        <button type=\"button\" class=\"cta\" data-role-entry=\"admin\" onclick=\"event.stopPropagation(); YMDesignMock.enterRole('admin','14-crm-admin.html')\">운영자 화면으로 보기 →</button>\n      </div>\n    </div>\n  </div>""")
p.write_text(text, encoding='utf-8')

# 09 expert
p = base / '09-standard-7axis.html'
text = p.read_text(encoding='utf-8')
text = text.replace(
"style=\"background: linear-gradient(135deg, #3b84f6, #49cda6); color:#fff; border-color:transparent;\"",
"style=\"background: linear-gradient(135deg, #2d6d88, #65b0d2); color:#fff; border-color:transparent;\"",
1)
text = text.replace(
"""  <div class=\"section\" style=\"margin-top:12px; padding:14px 18px; background:rgba(255,255,255,0.035)\">\n    <div style=\"display:flex; gap:14px; justify-content:space-between; align-items:center; flex-wrap:wrap;\">\n      <div>\n        <span class=\"chip role-b2b\" style=\"margin-bottom:8px\">전문가·협업 흐름</span>\n        <div style=\"font-weight:700; color:#fff; margin-bottom:4px\">지금 보는 메뉴는 해당 역할 기준으로 다시 정리된 화면입니다.</div>\n        <div style=\"font-size:13px; color:#9ca3b8\">표준, 정규화, 매핑, 공동연구, 파트너십처럼 내부 기준과 협업 화면만 모았습니다.</div>\n      </div>\n      <div style=\"display:flex; gap:8px; flex-wrap:wrap;\"><button type=\"button\" class=\"chip role-b2c\" onclick=\"YMDesignMock.enterRole('consumer','02-dashboard.html')\">일반 사용자 흐름 보기</button><button type=\"button\" class=\"chip role-b2c\" onclick=\"YMDesignMock.enterRole('consumer','17-mila-shop.html')\">상품·구매 흐름 보기</button><button type=\"button\" class=\"chip role-admin\" onclick=\"YMDesignMock.enterRole('admin','14-crm-admin.html')\">운영 화면 보기</button></div>\n    </div>\n  </div>""",
"""  <div class=\"section\" style=\"margin-top:12px; padding:16px 18px; background:linear-gradient(135deg, rgba(101,176,210,0.12), rgba(37,72,92,0.18)); border:1px solid rgba(101,176,210,0.24)\">\n    <div style=\"display:flex; gap:14px; justify-content:space-between; align-items:center; flex-wrap:wrap;\">\n      <div>\n        <span class=\"chip role-b2b\" style=\"margin-bottom:8px\">전문가 전용 작업 영역</span>\n        <div style=\"font-weight:800; color:#fff; margin-bottom:4px\">이 화면은 소비자용이 아니라 기준·검증·협업용입니다.</div>\n        <div style=\"font-size:13px; color:#b4c8d6\">표준, 정규화, 매핑, 공동연구, 파트너십처럼 내부 기준과 협업 화면만 남기고 소비자용 구매 메뉴는 제거했습니다.</div>\n      </div>\n      <div style=\"display:flex; gap:8px; flex-wrap:wrap;\"><button type=\"button\" class=\"chip role-b2c\" onclick=\"YMDesignMock.enterRole('consumer','02-dashboard.html')\">일반 사용자 흐름 보기</button><button type=\"button\" class=\"chip role-admin\" onclick=\"YMDesignMock.enterRole('admin','14-crm-admin.html')\">운영 화면 보기</button></div>\n    </div>\n  </div>""")
text = text.replace(
"""  <div class=\"section\">\n    <h1>연구 기준과 7축 체계</h1>\n    <p>이 화면은 일반 사용자 구매 화면이 아니라 전문가용 기준 화면입니다. YM Laboratory는 체질·증상·원료·조리·계절·주의·근거를 하나의 공통 언어로 정리한 7축 기준 체계를 운영합니다.</p>\n  </div>""",
"""  <div class=\"section\">\n    <span class=\"chip role-b2b\" style=\"margin-bottom:8px\">전문가 전용</span>\n    <h1>연구 기준과 7축 체계</h1>\n    <p>이 화면은 일반 사용자 구매 화면이 아니라 전문가용 기준 화면입니다. YM Laboratory는 체질·증상·원료·조리·계절·주의·근거를 하나의 공통 언어로 정리한 7축 기준 체계를 운영합니다.</p>\n    <div class=\"grid\" style=\"margin-top:14px\">\n      <div class=\"card\" style=\"border-color:rgba(101,176,210,0.30)\"><span class=\"chip role-b2b\" style=\"margin-bottom:8px\">기준</span><div class=\"title\">7축 공통 언어</div><div class=\"meta\">체질·증상·원료·조리·계절·주의·근거를 같은 프레임으로 검토</div></div>\n      <div class=\"card\" style=\"border-color:rgba(101,176,210,0.30)\"><span class=\"chip role-b2b\" style=\"margin-bottom:8px\">검증</span><div class=\"title\">정규화·예외 관리</div><div class=\"meta\">원료명, 동의어, 금기, 예외 케이스를 먼저 정리</div></div>\n      <div class=\"card\" style=\"border-color:rgba(101,176,210,0.30)\"><span class=\"chip role-b2b\" style=\"margin-bottom:8px\">협업</span><div class=\"title\">연구·파트너 연결</div><div class=\"meta\">대학, 셰프, 호텔, 브랜드 협업을 위한 기준 화면</div></div>\n    </div>\n  </div>""")
p.write_text(text, encoding='utf-8')

# 14 admin
p = base / '14-crm-admin.html'
text = p.read_text(encoding='utf-8')
text = text.replace(
"style=\"background: linear-gradient(135deg, #3b84f6, #49cda6); color:#fff; border-color:transparent;\"",
"style=\"background: linear-gradient(135deg, #6a620d, #a59a1b); color:#fff; border-color:transparent;\"",
1)
text = text.replace(
"""  <div class=\"section\" style=\"margin-top:12px; padding:14px 18px; background:rgba(255,255,255,0.035)\">\n    <div style=\"display:flex; gap:14px; justify-content:space-between; align-items:center; flex-wrap:wrap;\">\n      <div>\n        <span class=\"chip role-admin\" style=\"margin-bottom:8px\">운영·관리 흐름</span>\n        <div style=\"font-weight:700; color:#fff; margin-bottom:4px\">지금 보는 메뉴는 해당 역할 기준으로 다시 정리된 화면입니다.</div>\n        <div style=\"font-size:13px; color:#9ca3b8\">구독, 이탈위험, VIP, 캠페인 운영처럼 관리자가 바로 확인해야 할 화면만 모았습니다.</div>\n      </div>\n      <div style=\"display:flex; gap:8px; flex-wrap:wrap;\"><button type=\"button\" class=\"chip role-b2c\" onclick=\"YMDesignMock.enterRole('consumer','02-dashboard.html')\">일반 사용자 흐름 보기</button><button type=\"button\" class=\"chip role-b2c\" onclick=\"YMDesignMock.enterRole('consumer','17-mila-shop.html')\">상품·구매 흐름 보기</button></div>\n    </div>\n  </div>""",
"""  <div class=\"section\" style=\"margin-top:12px; padding:16px 18px; background:linear-gradient(135deg, rgba(127,119,18,0.18), rgba(70,65,14,0.18)); border:1px solid rgba(215,200,18,0.24)\">\n    <div style=\"display:flex; gap:14px; justify-content:space-between; align-items:center; flex-wrap:wrap;\">\n      <div>\n        <span class=\"chip role-admin\" style=\"margin-bottom:8px\">운영자 통제판</span>\n        <div style=\"font-weight:800; color:#fff; margin-bottom:4px\">이 화면은 운영자만 보는 관리 전용 화면입니다.</div>\n        <div style=\"font-size:13px; color:#d6d1a4\">구독, 이탈위험, VIP, 캠페인 운영처럼 관리자가 바로 확인해야 할 화면만 모았고 일반 사용자용 구매 흐름과 분리했습니다.</div>\n      </div>\n      <div style=\"display:flex; gap:8px; flex-wrap:wrap;\"><button type=\"button\" class=\"chip role-b2c\" onclick=\"YMDesignMock.enterRole('consumer','02-dashboard.html')\">일반 사용자 흐름 보기</button><button type=\"button\" class=\"chip role-b2b\" onclick=\"YMDesignMock.enterRole('expert','09-standard-7axis.html')\">전문가 흐름 보기</button></div>\n    </div>\n  </div>""")
text = text.replace(
"""  <div class=\"section\">\n    <h1>구독자 · 리드 · 운영 CRM</h1>\n    <p>운영자가 구독, 이탈위험, VIP, 캠페인을 관리하는 전용 화면입니다. 일반 사용자 루틴 화면과 분리된 운영 흐름으로 정리했습니다.</p>\n  </div>""",
"""  <div class=\"section\">\n    <span class=\"chip role-admin\" style=\"margin-bottom:8px\">운영 전용</span>\n    <h1>구독자 · 리드 · 운영 CRM</h1>\n    <p>운영자가 구독, 이탈위험, VIP, 캠페인을 관리하는 전용 화면입니다. 일반 사용자 루틴 화면과 분리된 운영 흐름으로 정리했습니다.</p>\n    <div class=\"grid\" style=\"margin-top:14px\">\n      <div class=\"card\" style=\"border-color:rgba(215,200,18,0.28)\"><span class=\"chip role-admin\" style=\"margin-bottom:8px\">모니터링</span><div class=\"title\">구독 상태 한눈에</div><div class=\"meta\">활성 구독, 이탈위험, VIP를 운영 지표로 바로 확인</div></div>\n      <div class=\"card\" style=\"border-color:rgba(215,200,18,0.28)\"><span class=\"chip role-admin\" style=\"margin-bottom:8px\">실행</span><div class=\"title\">캠페인 즉시 조정</div><div class=\"meta\">예약 발송, 쿠폰, 이슈 대상 관리를 운영 화면에서 실행</div></div>\n      <div class=\"card\" style=\"border-color:rgba(215,200,18,0.28)\"><span class=\"chip role-admin\" style=\"margin-bottom:8px\">분리</span><div class=\"title\">소비자 흐름과 완전 분리</div><div class=\"meta\">구매·루틴 UI 대신 관리 UI만 남겨 운영자 성격을 명확히 함</div></div>\n    </div>\n  </div>""")
p.write_text(text, encoding='utf-8')

# 17 shop
p = base / '17-mila-shop.html'
text = p.read_text(encoding='utf-8')
text = text.replace(
"""  <div class=\"section\" style=\"margin-top:12px; padding:14px 18px; background:rgba(255,255,255,0.035)\">\n    <div style=\"display:flex; gap:14px; justify-content:space-between; align-items:center; flex-wrap:wrap;\">\n      <div>\n        <span class=\"chip role-b2c\" style=\"margin-bottom:8px\">일반 사용자 흐름</span>\n        <div style=\"font-weight:700; color:#fff; margin-bottom:4px\">지금 보는 메뉴는 해당 역할 기준으로 다시 정리된 화면입니다.</div>\n        <div style=\"font-size:13px; color:#9ca3b8\">체질 진단, 루틴, 발효, 뷰티, 구매 화면만 먼저 보이도록 정리했습니다.</div>\n      </div>\n      <div style=\"display:flex; gap:8px; flex-wrap:wrap;\"><button type=\"button\" class=\"chip role-b2b\" onclick=\"YMDesignMock.enterRole('expert','09-standard-7axis.html')\">7축 기준 보기</button><button type=\"button\" class=\"chip role-b2b\" onclick=\"YMDesignMock.enterRole('expert','13-pro-community.html')\">전문가 협업 보기</button><button type=\"button\" class=\"chip role-admin\" onclick=\"YMDesignMock.enterRole('admin','14-crm-admin.html')\">운영 화면 보기</button></div>\n    </div>\n  </div>""",
"""  <div class=\"section\" style=\"margin-top:12px; padding:16px 18px; background:linear-gradient(135deg, rgba(59,132,246,0.10), rgba(73,205,166,0.08)); border:1px solid rgba(73,205,166,0.18)\">\n    <div style=\"display:flex; gap:14px; justify-content:space-between; align-items:center; flex-wrap:wrap;\">\n      <div>\n        <span class=\"chip role-b2c\" style=\"margin-bottom:8px\">일반 사용자 구매 화면</span>\n        <div style=\"font-weight:800; color:#fff; margin-bottom:4px\">여기는 실제 구매와 장바구니를 보는 소비자용 숍입니다.</div>\n        <div style=\"font-size:13px; color:#b8c6da\">상품 탐색, 담기, 결제 흐름을 중심으로 보여주고 연구 기준·운영 지표는 별도 화면으로 분리했습니다.</div>\n      </div>\n      <div style=\"display:flex; gap:8px; flex-wrap:wrap;\"><button type=\"button\" class=\"chip role-b2b\" onclick=\"YMDesignMock.enterRole('expert','09-standard-7axis.html')\">전문가 기준 보기</button><button type=\"button\" class=\"chip role-admin\" onclick=\"YMDesignMock.enterRole('admin','14-crm-admin.html')\">운영 화면 보기</button></div>\n    </div>\n  </div>""")
text = text.replace(
"""  <div class=\"section\">\n    <h1>MILA 프리미엄 숍</h1>\n    <p>일반 사용자가 실제로 둘러보고 담고 결제 흐름을 확인하는 구매 화면입니다. 한방 화장, 전통발효, 정기배송, VIP 상품까지 하나의 숍에서 연결하되, 전문가 기준은 별도 흐름으로 분리해 보여줍니다.</p>\n  </div>""",
"""  <div class=\"section\">\n    <span class=\"chip role-b2c\" style=\"margin-bottom:8px\">구매 전용</span>\n    <h1>MILA 프리미엄 숍</h1>\n    <p>일반 사용자가 실제로 둘러보고 담고 결제 흐름을 확인하는 구매 화면입니다. 한방 화장, 전통발효, 정기배송, VIP 상품까지 하나의 숍에서 연결하되, 전문가 기준은 별도 흐름으로 분리해 보여줍니다.</p>\n    <div class=\"row-list\" style=\"margin-top:14px\">\n      <div class=\"row\"><span>이 화면에서 하는 일</span><span>상품 탐색 · 장바구니 · 결제</span></div>\n      <div class=\"row\"><span>전문가 화면과의 차이</span><span>기준·검증 대신 구매 중심</span></div>\n      <div class=\"row\"><span>운영 화면과의 차이</span><span>KPI·캠페인 대신 고객 경험 중심</span></div>\n    </div>\n  </div>""")
p.write_text(text, encoding='utf-8')

print('cp09 final polish applied')
