"""
AgentExecution Model
=====================
Maps to ``agent_logs`` table (ACPP_DATABASE_SCHEMA §2.4).
Detailed operational logs generated by individual micro-agents.
"""

from __future__ import annotations

import uuid
from typing import TYPE_CHECKING

from sqlalchemy import CheckConstraint, ForeignKey, Index, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from acpp.db.base import Base, TimestampMixin

if TYPE_CHECKING:
    from acpp.models.workflow_history import WorkflowHistory


class AgentExecution(Base, TimestampMixin):
    """
    Micro-agent execution trace log entry.

    Each row represents a single action executed by one of the
    7 ACPP micro-agents within a workflow run.
    """

    __tablename__ = "agent_logs"

    # ── Primary Key ───────────────────────────────────────────────────
    log_id: Mapped[str] = mapped_column(
        String(64), primary_key=True, default=lambda: str(uuid.uuid4())
    )

    # ── Foreign Keys ──────────────────────────────────────────────────
    workflow_run_id: Mapped[str] = mapped_column(
        String(64),
        ForeignKey("workflow_history.workflow_run_id", ondelete="CASCADE"),
        nullable=False,
    )

    # ── Core Fields ───────────────────────────────────────────────────
    agent_id: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    action_name: Mapped[str] = mapped_column(String(64), nullable=False)
    log_level: Mapped[str] = mapped_column(String(8), nullable=False, default="INFO")
    message: Mapped[str] = mapped_column(Text, nullable=False)
    execution_time_ms: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # ── Relationships ─────────────────────────────────────────────────
    workflow: Mapped["WorkflowHistory"] = relationship(
        "WorkflowHistory", back_populates="agent_executions"
    )

    # ── Table constraints ─────────────────────────────────────────────
    __table_args__ = (
        CheckConstraint(
            "log_level IN ('INFO', 'WARN', 'ERROR', 'DEBUG')",
            name="ck_agent_log_level",
        ),
        Index("idx_agent_logs_wf", "workflow_run_id", "agent_id"),
    )

    def __repr__(self) -> str:
        return (
            f"<AgentExecution(log_id={self.log_id!r}, "
            f"agent={self.agent_id!r}, action={self.action_name!r})>"
        )
