"""
Writing Agent (ACPP-AG-03) Core Module
======================================
Transforms Structured Knowledge Assets into multi-channel content drafts
(Blog Markdown, HTML, Newsletter, Social Media, Technical Brief) under ADF v3.1.
Strictly preserves source Q-Code references and source traceability.
"""

import logging
from datetime import datetime, timezone
from typing import Any, Dict, List

from acpp.schemas.writing import ContentAsset, WritingRequest

logger = logging.getLogger("acpp.agents.writing")


class WritingAgent:
    """
    Writing Agent (ACPP-AG-03)
    Generates multi-channel content packages while preserving strict Q-Code provenance.
    """

    AGENT_ID = "ACPP-AG-03"
    AGENT_NAME = "Writing Agent"
    VERSION = "v1.0.0"

    def __init__(self) -> None:
        self.logger = logger

    def generate_metadata(
        self, asset: Dict[str, Any], request: WritingRequest, content_type: str
    ) -> Dict[str, Any]:
        """Generate standardized provenance metadata for content assets."""
        now_utc = datetime.now(timezone.utc)
        return {
            "q_code": request.q_code,
            "source_asset_id": request.knowledge_asset_id,
            "content_type": content_type,
            "target_audience": request.target_audience,
            "language": request.language,
            "tone": request.tone,
            "agent_id": self.AGENT_ID,
            "version": self.VERSION,
            "generated_at": now_utc.isoformat(),
        }

    def generate_blog_markdown(
        self, asset: Dict[str, Any], request: WritingRequest
    ) -> ContentAsset:
        """Generate Blog Markdown draft asset."""
        title = asset.get("title", "Structured Knowledge Review")
        summary = asset.get("summary", "Executive overview of findings.")
        claims = asset.get("claims", [])
        metadata = self.generate_metadata(asset, request, "blog")

        lines = [
            f"# {title}",
            "",
            f"**Q-Code:** {request.q_code}  ",
            f"**Source:** {request.knowledge_asset_id}  ",
            f"**Language:** {request.language} | **Tone:** {request.tone}",
            "",
            "## Summary",
            summary,
            "",
            "## Key Insights & Empirical Evidence",
        ]

        for claim in claims:
            statement = claim.get("statement", "")
            confidence = claim.get("confidence_score", 0.9)
            url = claim.get("citation_url")
            cite = f" ([Citation]({url}))" if url else ""
            lines.append(f"- {statement} (Confidence: {confidence}){cite}")

        lines.extend([
            "",
            "---",
            f"*Generated by ACPP Writing Agent ({self.AGENT_ID}) under ADF v3.1 Standards.*",
        ])

        body = "\n".join(lines)
        return ContentAsset(
            asset_type="blog",
            title=f"Blog Post: {title}",
            body=body,
            metadata=metadata,
        )

    def generate_html_content(
        self, asset: Dict[str, Any], request: WritingRequest
    ) -> ContentAsset:
        """Generate HTML Content draft asset."""
        title = asset.get("title", "Structured Knowledge Review")
        summary = asset.get("summary", "Executive overview of findings.")
        claims = asset.get("claims", [])
        metadata = self.generate_metadata(asset, request, "html")

        claims_html = ""
        for claim in claims:
            statement = claim.get("statement", "")
            confidence = claim.get("confidence_score", 0.9)
            claims_html += f"      <li><strong>{statement}</strong> (Confidence: {confidence})</li>\n"

        body = f"""<!DOCTYPE html>
<html lang="{request.language.lower()}">
<head>
  <meta charset="UTF-8">
  <title>{title}</title>
  <meta name="qcode" content="{request.q_code}">
  <meta name="source-asset-id" content="{request.knowledge_asset_id}">
</head>
<body>
  <article class="acpp-content-package">
    <header>
      <h1>{title}</h1>
      <p class="provenance-tag">Q-Code: {request.q_code} | Source: {request.knowledge_asset_id}</p>
    </header>
    <section class="summary">
      <h2>Executive Summary</h2>
      <p>{summary}</p>
    </section>
    <section class="evidence">
      <h2>Empirical Evidence</h2>
      <ul>
{claims_html}      </ul>
    </section>
    <footer>
      <p>Generated by ACPP Writing Agent ({self.AGENT_ID}) - {self.VERSION}</p>
    </footer>
  </article>
</body>
</html>"""

        return ContentAsset(
            asset_type="html",
            title=f"HTML Article: {title}",
            body=body,
            metadata=metadata,
        )

    def generate_newsletter_content(
        self, asset: Dict[str, Any], request: WritingRequest
    ) -> ContentAsset:
        """Generate Newsletter draft asset."""
        title = asset.get("title", "Structured Knowledge Digest")
        summary = asset.get("summary", "Key insights summary.")
        metadata = self.generate_metadata(asset, request, "newsletter")

        body = (
            f"SUBJECT: [ACPP Digest] {title}\n\n"
            f"Hello Reader,\n\n"
            f"Here is your latest technical briefing derived from Q-Code {request.q_code}:\n\n"
            f"SUMMARY:\n{summary}\n\n"
            f"Reference Knowledge Asset: {request.knowledge_asset_id}\n"
            f"Q-Code Index: {request.q_code}\n\n"
            f"Best regards,\nACPP Automated Content Dispatch Engine ({self.AGENT_ID})\n"
        )

        return ContentAsset(
            asset_type="newsletter",
            title=f"Newsletter: {title}",
            body=body,
            metadata=metadata,
        )

    def generate_social_content(
        self, asset: Dict[str, Any], request: WritingRequest
    ) -> ContentAsset:
        """Generate Social Media post draft asset."""
        title = asset.get("title", "Key Finding")
        metadata = self.generate_metadata(asset, request, "social")

        body = (
            f"🚀 Key Insight Update [{request.q_code}]: {title}\n\n"
            f"Empirical data verified under Source ID {request.knowledge_asset_id}.\n\n"
            f"#ACPP #AI #KnowledgeManagement #{request.q_code.replace('-', '_')}"
        )

        return ContentAsset(
            asset_type="social",
            title=f"Social Post: {title}",
            body=body,
            metadata=metadata,
        )

    def generate_technical_brief(
        self, asset: Dict[str, Any], request: WritingRequest
    ) -> ContentAsset:
        """Generate Technical Brief draft asset."""
        title = asset.get("title", "Technical Knowledge Brief")
        summary = asset.get("summary", "Technical overview.")
        claims = asset.get("claims", [])
        metadata = self.generate_metadata(asset, request, "technical_brief")

        lines = [
            f"TECHNICAL BRIEF: {title}",
            f"============================================================",
            f"Q-Code Reference    : {request.q_code}",
            f"Source Knowledge ID : {request.knowledge_asset_id}",
            f"Target Audience     : {request.target_audience}",
            f"Language            : {request.language}",
            f"============================================================",
            "",
            "1. EXECUTIVE OVERVIEW",
            summary,
            "",
            "2. VERIFIED CLAIMS & DATA POINTS",
        ]

        for idx, claim in enumerate(claims, 1):
            statement = claim.get("statement", "")
            confidence = claim.get("confidence_score", 0.9)
            lines.append(f"   2.{idx} Claim: {statement}")
            lines.append(f"       Confidence Score: {confidence}")

        lines.extend([
            "",
            "============================================================",
            f"END OF TECHNICAL BRIEF - AUTHOR {self.AGENT_ID}",
        ])

        body = "\n".join(lines)
        return ContentAsset(
            asset_type="technical_brief",
            title=f"Technical Brief: {title}",
            body=body,
            metadata=metadata,
        )

    def generate_content(
        self, knowledge_asset: Dict[str, Any], request: WritingRequest
    ) -> List[ContentAsset]:
        """
        Main entrypoint: Generate multi-channel content assets based on request.content_type.
        """
        self.logger.info(
            f"[{self.AGENT_ID}] Generating content type '{request.content_type}' for "
            f"asset '{request.knowledge_asset_id}' / Q-Code '{request.q_code}'"
        )

        ctype = request.content_type.lower()
        generators = {
            "blog": self.generate_blog_markdown,
            "html": self.generate_html_content,
            "newsletter": self.generate_newsletter_content,
            "social": self.generate_social_content,
            "technical_brief": self.generate_technical_brief,
        }

        if ctype in generators:
            return [generators[ctype](knowledge_asset, request)]

        # Default 'all': generate full multi-channel content package
        return [gen(knowledge_asset, request) for gen in generators.values()]
